apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: captureapi
  name: captureapi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: captureapi
    spec:
      containers:
      - env:
        - name: MONGOHOST
          value: mongodb://mongo/orders/
        - name: RABBITMQHOST
          value: amqp://rabbit:rabbit@rabbitmq:5672
        - name: TEAMNAME
          value: TEAM3
        image: team3acr.azurecr.io/shanepeckham/captureorderack:v3
        name: captureapi
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
