apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: fulfillapi
  name: fulfillapi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: fulfillapi
    spec:
      containers:
      - env:
        - name: MONGOHOST
          value: mongodb://mongo/orders/
        - name: TEAMNAME
          value: TEAM3
        image: team3acr.azurecr.io/shanepeckham/fulfillorderack:v3
        name: fulfillapi
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /orders
          name: fulfillapi
      restartPolicy: Always
      volumes:
      - name: fulfillapi
        persistentVolumeClaim:
          claimName: fulfillapi
status: {}
