apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: rabbit
        - name: RABBITMQ_DEFAULT_USER
          value: rabbit
        image: team3acr.azurecr.io/rabbitmq:3-management
        name: rabbitmq
        ports:
        - containerPort: 15672
        resources: {}
      restartPolicy: Always
status: {}
